export const WILAYAS = [
  { id: 1, nameAr: 'أدرار', nameFr: 'Adrar' },
  { id: 2, nameAr: 'الشلف', nameFr: 'Chlef' },
  { id: 3, nameAr: 'الأغواط', nameFr: 'Laghouat' },
  { id: 4, nameAr: 'أم البواقي', nameFr: 'Oum El Bouaghi' },
  { id: 5, nameAr: 'باتنة', nameFr: 'Batna' },
  { id: 6, nameAr: 'بجاية', nameFr: 'Béjaïa' },
  { id: 7, nameAr: 'بسكرة', nameFr: 'Biskra' },
  { id: 8, nameAr: 'بشار', nameFr: 'Béchar' },
  { id: 9, nameAr: 'البليدة', nameFr: 'Blida' },
  { id: 10, nameAr: 'البويرة', nameFr: 'Bouira' },
  { id: 11, nameAr: 'تمنراست', nameFr: 'Tamanrasset' },
  { id: 12, nameAr: 'تبسة', nameFr: 'Tébessa' },
  { id: 13, nameAr: 'تلمسان', nameFr: 'Tlemcen' },
  { id: 14, nameAr: 'تيارت', nameFr: 'Tiaret' },
  { id: 15, nameAr: 'تيزي وزو', nameFr: 'Tizi Ouzou' },
  { id: 16, nameAr: 'الجزائر العاصمة', nameFr: 'Alger' },
  { id: 17, nameAr: 'الجلفة', nameFr: 'Djelfa' },
  { id: 18, nameAr: 'جيجل', nameFr: 'Jijel' },
  { id: 19, nameAr: 'سطيف', nameFr: 'Sétif' },
  { id: 20, nameAr: 'سعيدة', nameFr: 'Saïda' },
  { id: 21, nameAr: 'سكيكدة', nameFr: 'Skikda' },
  { id: 22, nameAr: 'سيدي بلعباس', nameFr: 'Sidi Bel Abbès' },
  { id: 23, nameAr: 'عنابة', nameFr: 'Annaba' },
  { id: 24, nameAr: 'قالمة', nameFr: 'Guelma' },
  { id: 25, nameAr: 'قسنطينة', nameFr: 'Constantine' },
  { id: 26, nameAr: 'المدية', nameFr: 'Médéa' },
  { id: 27, nameAr: 'مستغانم', nameFr: 'Mostaganem' },
  { id: 28, nameAr: 'المسيلة', nameFr: 'M\'Sila' },
  { id: 29, nameAr: 'معسكر', nameFr: 'Mascara' },
  { id: 30, nameAr: 'ورقلة', nameFr: 'Ouargla' },
  { id: 31, nameAr: 'وهران', nameFr: 'Oran' },
  { id: 32, nameAr: 'البيض', nameFr: 'El Bayadh' },
  { id: 33, nameAr: 'إيليزي', nameFr: 'Illizi' },
  { id: 34, nameAr: 'برج بوعريريج', nameFr: 'Bordj Bou Arréridj' },
  { id: 35, nameAr: 'بومرداس', nameFr: 'Boumerdès' },
  { id: 36, nameAr: 'الطارف', nameFr: 'El Tarf' },
  { id: 37, nameAr: 'تندوف', nameFr: 'Tindouf' },
  { id: 38, nameAr: 'تسمسيلت', nameFr: 'Tissemsilt' },
  { id: 39, nameAr: 'الوادي', nameFr: 'El Oued' },
  { id: 40, nameAr: 'خنشلة', nameFr: 'Khenchela' },
  { id: 41, nameAr: 'سوق أهراس', nameFr: 'Souk Ahras' },
  { id: 42, nameAr: 'تيبازة', nameFr: 'Tipaza' },
  { id: 43, nameAr: 'ميلة', nameFr: 'Mila' },
  { id: 44, nameAr: 'عين الدفلى', nameFr: 'Aïn Defla' },
  { id: 45, nameAr: 'النعامة', nameFr: 'Naâma' },
  { id: 46, nameAr: 'عين تموشنت', nameFr: 'Aïn Témouchent' },
  { id: 47, nameAr: 'غرداية', nameFr: 'Ghardaïa' },
  { id: 48, nameAr: 'غليزان', nameFr: 'Relizane' },
  { id: 49, nameAr: 'تيميمون', nameFr: 'Timimoun' },
  { id: 50, nameAr: 'برج باجي مختار', nameFr: 'Bordj Badji Mokhtar' },
  { id: 51, nameAr: 'أولاد جلال', nameFr: 'Ouled Djellal' },
  { id: 52, nameAr: 'بني عباس', nameFr: 'Béni Abbès' },
  { id: 53, nameAr: 'عين صالح', nameFr: 'In Salah' },
  { id: 54, nameAr: 'عين قزام', nameFr: 'In Guezzam' },
  { id: 55, nameAr: 'تقرت', nameFr: 'Touggourt' },
  { id: 56, nameAr: 'جانت', nameFr: 'Djanet' },
  { id: 57, nameAr: 'المغير', nameFr: 'El M\'Ghair' },
  { id: 58, nameAr: 'المنيعة', nameFr: 'El Meniaa' }
];
